[colors.primary]
background = "#000000"
foreground = "#f5f5f5"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
y = 8

[window]
decorations = "none"
opacity = 0.9

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 12
y = 12
