[colors.primary]
background = "#000000"
foreground = "#c5c8c6"

[font]
size = 14

[font.normal]
family = "BlexMono Nerd Font"
# family = "BigBlueTermPlus Nerd Font"
# family = "GohuFont 14 Nerd Font Propo"
# family = "GoMono Nerd Font"

[font.offset]
y = 6

[window]
decorations = "none"
opacity = 0.8

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 8
y = 8
